#!/bin/bash

timeout=1         # delay between checks
pingip=$1   # what to ping
slave1="eth1"
slave2="eth2"
slave1_mac="00:0c:29:fa:30:a9"
slave2_mac="00:0c:29:fa:30:b3"

LOG_FILE="/var/log/ping-log"

while true; do
    LOG_TIME=`date +%b' '%d' '%T`
    if ping -I bond1 -q -c 2 "$pingip" >> /dev/null ; then
        printf "ping is good\n"
    else
        printf "ping is bad\n"

        t1=$(cat /proc/net/bonding/bond1 | grep -o "Currently Active Slave: $slave1")

        if [ "$t1" != "" ]; then
            printf "Primary slave is $slave1\n"
            ifdown $slave1 && ifup $slave2
            ifconfig bond1 hw ether $slave2_mac
        else
            printf "Primary slave is $slave2\n"
            ifdown $slave2 && ifup $slave1
            ifconfig bond1 hw ether $slave1_mac
        fi
        cat /proc/net/bonding/bond1
    fi
    sleep "$timeout"
done
